(cl:in-package ros_sensor_msgs-msg)
(cl:export '(PSEUDODOPPLERDIFFS-VAL
          PSEUDODOPPLERDIFFS
          PSEUDODOPPLERDIFFASSURANCELEVEL-VAL
          PSEUDODOPPLERDIFFASSURANCELEVEL
          CARRIERTONOISECHECKDATA-VAL
          CARRIERTONOISECHECKDATA
          CNOCHECKASSURANCELEVEL-VAL
          CNOCHECKASSURANCELEVEL
))