(cl:in-package ros_sensor_msgs-msg)
(cl:export '(REMOTENODEIP-VAL
          REMOTENODEIP
          REMOTEPOSITION-VAL
          REMOTEPOSITION
          RFRANGE-VAL
          RFRANGE
          NODERANGE-VAL
          NODERANGE
          RANGECHECKASSURANCELEVEL-VAL
          RANGECHECKASSURANCELEVEL
          SINGLEDIFFERENCES-VAL
          SINGLEDIFFERENCES
          BASEPRN-VAL
          BASEPRN
          DOUBLEDIFFERENCES-VAL
          DOUBLEDIFFERENCES
          DIFFCHECKASSURANCELEVEL-VAL
          DIFFCHECKASSURANCELEVEL
))