(cl:in-package ros_sensor_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          VEHICLESPEED-VAL
          VEHICLESPEED
          YAWRATE-VAL
          YAWRATE
          FRONTLEFTWHEELSPEED-VAL
          FRONTLEFTWHEELSPEED
          FRONTRIGHTWHEELSPEED-VAL
          FRONTRIGHTWHEELSPEED
          REARLEFTWHEELSPEED-VAL
          REARLEFTWHEELSPEED
          REARRIGHTWHEELSPEED-VAL
          REARRIGHTWHEELSPEED
          STEERANGLE-VAL
          STEERANGLE
          STEERANGLERATE-VAL
          STEERANGLERATE
          FRONTLEFTTIREPRESSURE-VAL
          FRONTLEFTTIREPRESSURE
          FRONTRIGHTTIREPRESSURE-VAL
          FRONTRIGHTTIREPRESSURE
          REARLEFTTIREPRESSURE-VAL
          REARLEFTTIREPRESSURE
          REARRIGHTTIREPRESSURE-VAL
          REARRIGHTTIREPRESSURE
))