(cl:in-package ros_sensor_msgs-msg)
(cl:export '(TIMEOFVALIDITY-VAL
          TIMEOFVALIDITY
          DATAVALID-VAL
          DATAVALID
          NETWORKDIFFERENCECOUNTS-VAL
          NETWORKDIFFERENCECOUNTS
          NETWORKDRIFTCOUNTS-VAL
          NETWORKDRIFTCOUNTS
          OSCILLATORFREQEST-VAL
          OSCILLATORFREQEST
          NETWORKDIFFERENCECMDCOUNTS-VAL
          NETWORKDIFFERENCECMDCOUNTS
          NETWORKDRIFTCMDCOUNTS-VAL
          NETWORKDRIFTCMDCOUNTS
          NETWORKPPSCOUNT-VAL
          NETWORKPPSCOUNT
          GPSPPSCOUNT-VAL
          GPSPPSCOUNT
))