(cl:in-package ros_sensor_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          TAGS-VAL
          TAGS
          FIX-VAL
          FIX
          NUMSATELLITESAVAILABLE-VAL
          NUMSATELLITESAVAILABLE
          TIMESINCELASTFIX-VAL
          TIMESINCELASTFIX
          AVAILABLEEPHEMERIS-VAL
          AVAILABLEEPHEMERIS
          AVAILABLEALMANAC-VAL
          AVAILABLEALMANAC
          UTCIONOAVAILABLE-VAL
          UTCIONOAVAILABLE
          NETWORKTIMEOFFSET-VAL
          NETWORKTIMEOFFSET
          COMPUTERTIMEOFFSET-VAL
          COMPUTERTIMEOFFSET
          ASSURANCE-VAL
          ASSURANCE
          ASSURANCECHECKVAL-VAL
          ASSURANCECHECKVAL
          ISSTALE-VAL
          ISSTALE
))