// Generated by gencpp from file tdcp/TdcpOutput.msg
// DO NOT EDIT!


#ifndef TDCP_MESSAGE_TDCPOUTPUT_H
#define TDCP_MESSAGE_TDCPOUTPUT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <ros_sensor_msgs/GpsTime.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>

namespace tdcp
{
template <class ContainerAllocator>
struct TdcpOutput_
{
  typedef TdcpOutput_<ContainerAllocator> Type;

  TdcpOutput_()
    : header()
    , gpsTime()
    , psrSolEcef()
    , psrSolEcefCovariance()
    , rpvEcef()
    , rpvEcefCovariance()
    , rpvNorm(0.0)  {
      psrSolEcefCovariance.assign(0.0);

      rpvEcefCovariance.assign(0.0);
  }
  TdcpOutput_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , gpsTime(_alloc)
    , psrSolEcef(_alloc)
    , psrSolEcefCovariance()
    , rpvEcef(_alloc)
    , rpvEcefCovariance()
    , rpvNorm(0.0)  {
  (void)_alloc;
      psrSolEcefCovariance.assign(0.0);

      rpvEcefCovariance.assign(0.0);
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::ros_sensor_msgs::GpsTime_<ContainerAllocator>  _gpsTime_type;
  _gpsTime_type gpsTime;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _psrSolEcef_type;
  _psrSolEcef_type psrSolEcef;

   typedef boost::array<float, 9>  _psrSolEcefCovariance_type;
  _psrSolEcefCovariance_type psrSolEcefCovariance;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _rpvEcef_type;
  _rpvEcef_type rpvEcef;

   typedef boost::array<float, 9>  _rpvEcefCovariance_type;
  _rpvEcefCovariance_type rpvEcefCovariance;

   typedef float _rpvNorm_type;
  _rpvNorm_type rpvNorm;





  typedef boost::shared_ptr< ::tdcp::TdcpOutput_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tdcp::TdcpOutput_<ContainerAllocator> const> ConstPtr;

}; // struct TdcpOutput_

typedef ::tdcp::TdcpOutput_<std::allocator<void> > TdcpOutput;

typedef boost::shared_ptr< ::tdcp::TdcpOutput > TdcpOutputPtr;
typedef boost::shared_ptr< ::tdcp::TdcpOutput const> TdcpOutputConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tdcp::TdcpOutput_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tdcp::TdcpOutput_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tdcp

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'tdcp': ['/home/christian/lateralOffset/src/tdcp/msg'], 'ros_sensor_msgs': ['/home/christian/lateralOffset/src/ros-sensor-msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tdcp::TdcpOutput_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tdcp::TdcpOutput_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tdcp::TdcpOutput_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tdcp::TdcpOutput_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tdcp::TdcpOutput_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tdcp::TdcpOutput_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tdcp::TdcpOutput_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2353195a8a8998915590d5121e0ba66f";
  }

  static const char* value(const ::tdcp::TdcpOutput_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2353195a8a899891ULL;
  static const uint64_t static_value2 = 0x5590d5121e0ba66fULL;
};

template<class ContainerAllocator>
struct DataType< ::tdcp::TdcpOutput_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tdcp/TdcpOutput";
  }

  static const char* value(const ::tdcp::TdcpOutput_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tdcp::TdcpOutput_<ContainerAllocator> >
{
  static const char* value()
  {
    return "## TdcpOutput\n\
\n\
std_msgs/Header          header\n\
ros_sensor_msgs/GpsTime  gpsTime\n\
geometry_msgs/Vector3    psrSolEcef\n\
float32[9]               psrSolEcefCovariance\n\
geometry_msgs/Vector3    rpvEcef\n\
float32[9]               rpvEcefCovariance\n\
float32                  rpvNorm\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: ros_sensor_msgs/GpsTime\n\
## GPS time structure\n\
uint32          gps_week        # Full GPS week from (0:0:00 Jan 06, 1980)\n\
float64         gps_seconds     # GPS seconds into week [sec]\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
# It is only meant to represent a direction. Therefore, it does not\n\
# make sense to apply a translation to it (e.g., when applying a \n\
# generic rigid transformation to a Vector3, tf2 will only apply the\n\
# rotation). If you want your data to be translatable too, use the\n\
# geometry_msgs/Point message instead.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::tdcp::TdcpOutput_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tdcp::TdcpOutput_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.gpsTime);
      stream.next(m.psrSolEcef);
      stream.next(m.psrSolEcefCovariance);
      stream.next(m.rpvEcef);
      stream.next(m.rpvEcefCovariance);
      stream.next(m.rpvNorm);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TdcpOutput_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tdcp::TdcpOutput_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tdcp::TdcpOutput_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "gpsTime: ";
    s << std::endl;
    Printer< ::ros_sensor_msgs::GpsTime_<ContainerAllocator> >::stream(s, indent + "  ", v.gpsTime);
    s << indent << "psrSolEcef: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.psrSolEcef);
    s << indent << "psrSolEcefCovariance[]" << std::endl;
    for (size_t i = 0; i < v.psrSolEcefCovariance.size(); ++i)
    {
      s << indent << "  psrSolEcefCovariance[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.psrSolEcefCovariance[i]);
    }
    s << indent << "rpvEcef: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.rpvEcef);
    s << indent << "rpvEcefCovariance[]" << std::endl;
    for (size_t i = 0; i < v.rpvEcefCovariance.size(); ++i)
    {
      s << indent << "  rpvEcefCovariance[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.rpvEcefCovariance[i]);
    }
    s << indent << "rpvNorm: ";
    Printer<float>::stream(s, indent + "  ", v.rpvNorm);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TDCP_MESSAGE_TDCPOUTPUT_H
