// Generated by gencpp from file ros_sensor_msgs/CmdGpsAssistSrvRequest.msg
// DO NOT EDIT!


#ifndef ROS_SENSOR_MSGS_MESSAGE_CMDGPSASSISTSRVREQUEST_H
#define ROS_SENSOR_MSGS_MESSAGE_CMDGPSASSISTSRVREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <ros_sensor_msgs/CmdGpsAssist.h>

namespace ros_sensor_msgs
{
template <class ContainerAllocator>
struct CmdGpsAssistSrvRequest_
{
  typedef CmdGpsAssistSrvRequest_<ContainerAllocator> Type;

  CmdGpsAssistSrvRequest_()
    : assist()  {
    }
  CmdGpsAssistSrvRequest_(const ContainerAllocator& _alloc)
    : assist(_alloc)  {
  (void)_alloc;
    }



   typedef  ::ros_sensor_msgs::CmdGpsAssist_<ContainerAllocator>  _assist_type;
  _assist_type assist;





  typedef boost::shared_ptr< ::ros_sensor_msgs::CmdGpsAssistSrvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_sensor_msgs::CmdGpsAssistSrvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct CmdGpsAssistSrvRequest_

typedef ::ros_sensor_msgs::CmdGpsAssistSrvRequest_<std::allocator<void> > CmdGpsAssistSrvRequest;

typedef boost::shared_ptr< ::ros_sensor_msgs::CmdGpsAssistSrvRequest > CmdGpsAssistSrvRequestPtr;
typedef boost::shared_ptr< ::ros_sensor_msgs::CmdGpsAssistSrvRequest const> CmdGpsAssistSrvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_sensor_msgs::CmdGpsAssistSrvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_sensor_msgs::CmdGpsAssistSrvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ros_sensor_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'ros_sensor_msgs': ['/home/christian/lateralOffset/src/ros-sensor-msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ros_sensor_msgs::CmdGpsAssistSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_sensor_msgs::CmdGpsAssistSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_sensor_msgs::CmdGpsAssistSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_sensor_msgs::CmdGpsAssistSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_sensor_msgs::CmdGpsAssistSrvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_sensor_msgs::CmdGpsAssistSrvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_sensor_msgs::CmdGpsAssistSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dbb57e1d99c69fb9537031facc1018c7";
  }

  static const char* value(const ::ros_sensor_msgs::CmdGpsAssistSrvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdbb57e1d99c69fb9ULL;
  static const uint64_t static_value2 = 0x537031facc1018c7ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_sensor_msgs::CmdGpsAssistSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_sensor_msgs/CmdGpsAssistSrvRequest";
  }

  static const char* value(const ::ros_sensor_msgs::CmdGpsAssistSrvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_sensor_msgs::CmdGpsAssistSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "CmdGpsAssist assist\n\
\n\
================================================================================\n\
MSG: ros_sensor_msgs/CmdGpsAssist\n\
bool assist_time\n\
bool assist_position\n\
bool assist_gps_ephemeris\n\
bool assist_gps_almanac\n\
bool assist_gps_utc_iono\n\
bool assist_precise_time\n\
";
  }

  static const char* value(const ::ros_sensor_msgs::CmdGpsAssistSrvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_sensor_msgs::CmdGpsAssistSrvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.assist);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CmdGpsAssistSrvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_sensor_msgs::CmdGpsAssistSrvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_sensor_msgs::CmdGpsAssistSrvRequest_<ContainerAllocator>& v)
  {
    s << indent << "assist: ";
    s << std::endl;
    Printer< ::ros_sensor_msgs::CmdGpsAssist_<ContainerAllocator> >::stream(s, indent + "  ", v.assist);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_SENSOR_MSGS_MESSAGE_CMDGPSASSISTSRVREQUEST_H
