// Generated by gencpp from file ros_sensor_msgs/CsacStatus.msg
// DO NOT EDIT!


#ifndef ROS_SENSOR_MSGS_MESSAGE_CSACSTATUS_H
#define ROS_SENSOR_MSGS_MESSAGE_CSACSTATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_sensor_msgs
{
template <class ContainerAllocator>
struct CsacStatus_
{
  typedef CsacStatus_<ContainerAllocator> Type;

  CsacStatus_()
    : status(0)  {
    }
  CsacStatus_(const ContainerAllocator& _alloc)
    : status(0)  {
  (void)_alloc;
    }



   typedef uint8_t _status_type;
  _status_type status;



  enum {
    Initialization = 0u,
    Steering = 1u,
    Locked = 2u,
    Unknown = 3u,
  };


  typedef boost::shared_ptr< ::ros_sensor_msgs::CsacStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_sensor_msgs::CsacStatus_<ContainerAllocator> const> ConstPtr;

}; // struct CsacStatus_

typedef ::ros_sensor_msgs::CsacStatus_<std::allocator<void> > CsacStatus;

typedef boost::shared_ptr< ::ros_sensor_msgs::CsacStatus > CsacStatusPtr;
typedef boost::shared_ptr< ::ros_sensor_msgs::CsacStatus const> CsacStatusConstPtr;

// constants requiring out of line definition

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_sensor_msgs::CsacStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_sensor_msgs::CsacStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ros_sensor_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'ros_sensor_msgs': ['/home/christian/lateralOffset/src/ros-sensor-msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ros_sensor_msgs::CsacStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_sensor_msgs::CsacStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_sensor_msgs::CsacStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_sensor_msgs::CsacStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_sensor_msgs::CsacStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_sensor_msgs::CsacStatus_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_sensor_msgs::CsacStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1736dd09b796bd8043d007e2b2955c9a";
  }

  static const char* value(const ::ros_sensor_msgs::CsacStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1736dd09b796bd80ULL;
  static const uint64_t static_value2 = 0x43d007e2b2955c9aULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_sensor_msgs::CsacStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_sensor_msgs/CsacStatus";
  }

  static const char* value(const ::ros_sensor_msgs::CsacStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_sensor_msgs::CsacStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "## CsacStatus\n\
\n\
uint8 Initialization = 0\n\
uint8 Steering       = 1\n\
uint8 Locked         = 2\n\
uint8 Unknown        = 3\n\
\n\
uint8 status\n\
";
  }

  static const char* value(const ::ros_sensor_msgs::CsacStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_sensor_msgs::CsacStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CsacStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_sensor_msgs::CsacStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_sensor_msgs::CsacStatus_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_SENSOR_MSGS_MESSAGE_CSACSTATUS_H
