// Generated by gencpp from file ros_sensor_msgs/GpsAssistSrv.msg
// DO NOT EDIT!


#ifndef ROS_SENSOR_MSGS_MESSAGE_GPSASSISTSRV_H
#define ROS_SENSOR_MSGS_MESSAGE_GPSASSISTSRV_H

#include <ros/service_traits.h>


#include <ros_sensor_msgs/GpsAssistSrvRequest.h>
#include <ros_sensor_msgs/GpsAssistSrvResponse.h>


namespace ros_sensor_msgs
{

struct GpsAssistSrv
{

typedef GpsAssistSrvRequest Request;
typedef GpsAssistSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GpsAssistSrv
} // namespace ros_sensor_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_sensor_msgs::GpsAssistSrv > {
  static const char* value()
  {
    return "90343e3974f5bb94a900d205e0870ced";
  }

  static const char* value(const ::ros_sensor_msgs::GpsAssistSrv&) { return value(); }
};

template<>
struct DataType< ::ros_sensor_msgs::GpsAssistSrv > {
  static const char* value()
  {
    return "ros_sensor_msgs/GpsAssistSrv";
  }

  static const char* value(const ::ros_sensor_msgs::GpsAssistSrv&) { return value(); }
};


// service_traits::MD5Sum< ::ros_sensor_msgs::GpsAssistSrvRequest> should match 
// service_traits::MD5Sum< ::ros_sensor_msgs::GpsAssistSrv > 
template<>
struct MD5Sum< ::ros_sensor_msgs::GpsAssistSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_sensor_msgs::GpsAssistSrv >::value();
  }
  static const char* value(const ::ros_sensor_msgs::GpsAssistSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_sensor_msgs::GpsAssistSrvRequest> should match 
// service_traits::DataType< ::ros_sensor_msgs::GpsAssistSrv > 
template<>
struct DataType< ::ros_sensor_msgs::GpsAssistSrvRequest>
{
  static const char* value()
  {
    return DataType< ::ros_sensor_msgs::GpsAssistSrv >::value();
  }
  static const char* value(const ::ros_sensor_msgs::GpsAssistSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_sensor_msgs::GpsAssistSrvResponse> should match 
// service_traits::MD5Sum< ::ros_sensor_msgs::GpsAssistSrv > 
template<>
struct MD5Sum< ::ros_sensor_msgs::GpsAssistSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_sensor_msgs::GpsAssistSrv >::value();
  }
  static const char* value(const ::ros_sensor_msgs::GpsAssistSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_sensor_msgs::GpsAssistSrvResponse> should match 
// service_traits::DataType< ::ros_sensor_msgs::GpsAssistSrv > 
template<>
struct DataType< ::ros_sensor_msgs::GpsAssistSrvResponse>
{
  static const char* value()
  {
    return DataType< ::ros_sensor_msgs::GpsAssistSrv >::value();
  }
  static const char* value(const ::ros_sensor_msgs::GpsAssistSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_SENSOR_MSGS_MESSAGE_GPSASSISTSRV_H
