// Generated by gencpp from file ros_sensor_msgs/LlhPosition.msg
// DO NOT EDIT!


#ifndef ROS_SENSOR_MSGS_MESSAGE_LLHPOSITION_H
#define ROS_SENSOR_MSGS_MESSAGE_LLHPOSITION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_sensor_msgs
{
template <class ContainerAllocator>
struct LlhPosition_
{
  typedef LlhPosition_<ContainerAllocator> Type;

  LlhPosition_()
    : latitude(0.0)
    , longitude(0.0)
    , altitude(0.0)
    , horizontalAccuracy(0)
    , verticalAccuracy(0)  {
    }
  LlhPosition_(const ContainerAllocator& _alloc)
    : latitude(0.0)
    , longitude(0.0)
    , altitude(0.0)
    , horizontalAccuracy(0)
    , verticalAccuracy(0)  {
  (void)_alloc;
    }



   typedef double _latitude_type;
  _latitude_type latitude;

   typedef double _longitude_type;
  _longitude_type longitude;

   typedef double _altitude_type;
  _altitude_type altitude;

   typedef uint16_t _horizontalAccuracy_type;
  _horizontalAccuracy_type horizontalAccuracy;

   typedef uint16_t _verticalAccuracy_type;
  _verticalAccuracy_type verticalAccuracy;





  typedef boost::shared_ptr< ::ros_sensor_msgs::LlhPosition_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_sensor_msgs::LlhPosition_<ContainerAllocator> const> ConstPtr;

}; // struct LlhPosition_

typedef ::ros_sensor_msgs::LlhPosition_<std::allocator<void> > LlhPosition;

typedef boost::shared_ptr< ::ros_sensor_msgs::LlhPosition > LlhPositionPtr;
typedef boost::shared_ptr< ::ros_sensor_msgs::LlhPosition const> LlhPositionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_sensor_msgs::LlhPosition_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_sensor_msgs::LlhPosition_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ros_sensor_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'ros_sensor_msgs': ['/home/christian/lateralOffset/src/ros-sensor-msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ros_sensor_msgs::LlhPosition_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_sensor_msgs::LlhPosition_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_sensor_msgs::LlhPosition_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_sensor_msgs::LlhPosition_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_sensor_msgs::LlhPosition_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_sensor_msgs::LlhPosition_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_sensor_msgs::LlhPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c6f425fbcae84dae779ac1c441d3712e";
  }

  static const char* value(const ::ros_sensor_msgs::LlhPosition_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc6f425fbcae84daeULL;
  static const uint64_t static_value2 = 0x779ac1c441d3712eULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_sensor_msgs::LlhPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_sensor_msgs/LlhPosition";
  }

  static const char* value(const ::ros_sensor_msgs::LlhPosition_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_sensor_msgs::LlhPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# # LlhPosition\n\
\n\
float64                  latitude   # [deg]\n\
float64                  longitude  # [deg]\n\
float64                  altitude   # [m]\n\
uint16                   horizontalAccuracy\n\
uint16                   verticalAccuracy\n\
";
  }

  static const char* value(const ::ros_sensor_msgs::LlhPosition_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_sensor_msgs::LlhPosition_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.latitude);
      stream.next(m.longitude);
      stream.next(m.altitude);
      stream.next(m.horizontalAccuracy);
      stream.next(m.verticalAccuracy);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LlhPosition_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_sensor_msgs::LlhPosition_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_sensor_msgs::LlhPosition_<ContainerAllocator>& v)
  {
    s << indent << "latitude: ";
    Printer<double>::stream(s, indent + "  ", v.latitude);
    s << indent << "longitude: ";
    Printer<double>::stream(s, indent + "  ", v.longitude);
    s << indent << "altitude: ";
    Printer<double>::stream(s, indent + "  ", v.altitude);
    s << indent << "horizontalAccuracy: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.horizontalAccuracy);
    s << indent << "verticalAccuracy: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.verticalAccuracy);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_SENSOR_MSGS_MESSAGE_LLHPOSITION_H
