// Generated by gencpp from file ros_sensor_msgs/PpsOffsetCmd.msg
// DO NOT EDIT!


#ifndef ROS_SENSOR_MSGS_MESSAGE_PPSOFFSETCMD_H
#define ROS_SENSOR_MSGS_MESSAGE_PPSOFFSETCMD_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace ros_sensor_msgs
{
template <class ContainerAllocator>
struct PpsOffsetCmd_
{
  typedef PpsOffsetCmd_<ContainerAllocator> Type;

  PpsOffsetCmd_()
    : header()
    , offset_counts(0)
    , drift_counts(0)  {
    }
  PpsOffsetCmd_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , offset_counts(0)
    , drift_counts(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _offset_counts_type;
  _offset_counts_type offset_counts;

   typedef int32_t _drift_counts_type;
  _drift_counts_type drift_counts;





  typedef boost::shared_ptr< ::ros_sensor_msgs::PpsOffsetCmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_sensor_msgs::PpsOffsetCmd_<ContainerAllocator> const> ConstPtr;

}; // struct PpsOffsetCmd_

typedef ::ros_sensor_msgs::PpsOffsetCmd_<std::allocator<void> > PpsOffsetCmd;

typedef boost::shared_ptr< ::ros_sensor_msgs::PpsOffsetCmd > PpsOffsetCmdPtr;
typedef boost::shared_ptr< ::ros_sensor_msgs::PpsOffsetCmd const> PpsOffsetCmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_sensor_msgs::PpsOffsetCmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_sensor_msgs::PpsOffsetCmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ros_sensor_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'ros_sensor_msgs': ['/home/christian/lateralOffset/src/ros-sensor-msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ros_sensor_msgs::PpsOffsetCmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_sensor_msgs::PpsOffsetCmd_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_sensor_msgs::PpsOffsetCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_sensor_msgs::PpsOffsetCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_sensor_msgs::PpsOffsetCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_sensor_msgs::PpsOffsetCmd_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_sensor_msgs::PpsOffsetCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9fc7471197658b908cb56e3b379ad9ed";
  }

  static const char* value(const ::ros_sensor_msgs::PpsOffsetCmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9fc7471197658b90ULL;
  static const uint64_t static_value2 = 0x8cb56e3b379ad9edULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_sensor_msgs::PpsOffsetCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_sensor_msgs/PpsOffsetCmd";
  }

  static const char* value(const ::ros_sensor_msgs::PpsOffsetCmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_sensor_msgs::PpsOffsetCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
std_msgs/Header   header\n\
int32             offset_counts\n\
int32             drift_counts\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::ros_sensor_msgs::PpsOffsetCmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_sensor_msgs::PpsOffsetCmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.offset_counts);
      stream.next(m.drift_counts);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PpsOffsetCmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_sensor_msgs::PpsOffsetCmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_sensor_msgs::PpsOffsetCmd_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "offset_counts: ";
    Printer<int32_t>::stream(s, indent + "  ", v.offset_counts);
    s << indent << "drift_counts: ";
    Printer<int32_t>::stream(s, indent + "  ", v.drift_counts);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_SENSOR_MSGS_MESSAGE_PPSOFFSETCMD_H
