// Generated by gencpp from file ros_sensor_msgs/RcvrZeroize.msg
// DO NOT EDIT!


#ifndef ROS_SENSOR_MSGS_MESSAGE_RCVRZEROIZE_H
#define ROS_SENSOR_MSGS_MESSAGE_RCVRZEROIZE_H

#include <ros/service_traits.h>


#include <ros_sensor_msgs/RcvrZeroizeRequest.h>
#include <ros_sensor_msgs/RcvrZeroizeResponse.h>


namespace ros_sensor_msgs
{

struct RcvrZeroize
{

typedef RcvrZeroizeRequest Request;
typedef RcvrZeroizeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RcvrZeroize
} // namespace ros_sensor_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_sensor_msgs::RcvrZeroize > {
  static const char* value()
  {
    return "1a6092fd53941ce04a5c576a57bbdbb6";
  }

  static const char* value(const ::ros_sensor_msgs::RcvrZeroize&) { return value(); }
};

template<>
struct DataType< ::ros_sensor_msgs::RcvrZeroize > {
  static const char* value()
  {
    return "ros_sensor_msgs/RcvrZeroize";
  }

  static const char* value(const ::ros_sensor_msgs::RcvrZeroize&) { return value(); }
};


// service_traits::MD5Sum< ::ros_sensor_msgs::RcvrZeroizeRequest> should match 
// service_traits::MD5Sum< ::ros_sensor_msgs::RcvrZeroize > 
template<>
struct MD5Sum< ::ros_sensor_msgs::RcvrZeroizeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_sensor_msgs::RcvrZeroize >::value();
  }
  static const char* value(const ::ros_sensor_msgs::RcvrZeroizeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_sensor_msgs::RcvrZeroizeRequest> should match 
// service_traits::DataType< ::ros_sensor_msgs::RcvrZeroize > 
template<>
struct DataType< ::ros_sensor_msgs::RcvrZeroizeRequest>
{
  static const char* value()
  {
    return DataType< ::ros_sensor_msgs::RcvrZeroize >::value();
  }
  static const char* value(const ::ros_sensor_msgs::RcvrZeroizeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_sensor_msgs::RcvrZeroizeResponse> should match 
// service_traits::MD5Sum< ::ros_sensor_msgs::RcvrZeroize > 
template<>
struct MD5Sum< ::ros_sensor_msgs::RcvrZeroizeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_sensor_msgs::RcvrZeroize >::value();
  }
  static const char* value(const ::ros_sensor_msgs::RcvrZeroizeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_sensor_msgs::RcvrZeroizeResponse> should match 
// service_traits::DataType< ::ros_sensor_msgs::RcvrZeroize > 
template<>
struct DataType< ::ros_sensor_msgs::RcvrZeroizeResponse>
{
  static const char* value()
  {
    return DataType< ::ros_sensor_msgs::RcvrZeroize >::value();
  }
  static const char* value(const ::ros_sensor_msgs::RcvrZeroizeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_SENSOR_MSGS_MESSAGE_RCVRZEROIZE_H
