// Generated by gencpp from file ros_sensor_msgs/RcvrZeroizeRequest.msg
// DO NOT EDIT!


#ifndef ROS_SENSOR_MSGS_MESSAGE_RCVRZEROIZEREQUEST_H
#define ROS_SENSOR_MSGS_MESSAGE_RCVRZEROIZEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_sensor_msgs
{
template <class ContainerAllocator>
struct RcvrZeroizeRequest_
{
  typedef RcvrZeroizeRequest_<ContainerAllocator> Type;

  RcvrZeroizeRequest_()
    : clear_keys(false)
    , clear_rcvr_data(false)
    , clear_position_and_time(false)  {
    }
  RcvrZeroizeRequest_(const ContainerAllocator& _alloc)
    : clear_keys(false)
    , clear_rcvr_data(false)
    , clear_position_and_time(false)  {
  (void)_alloc;
    }



   typedef uint8_t _clear_keys_type;
  _clear_keys_type clear_keys;

   typedef uint8_t _clear_rcvr_data_type;
  _clear_rcvr_data_type clear_rcvr_data;

   typedef uint8_t _clear_position_and_time_type;
  _clear_position_and_time_type clear_position_and_time;





  typedef boost::shared_ptr< ::ros_sensor_msgs::RcvrZeroizeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_sensor_msgs::RcvrZeroizeRequest_<ContainerAllocator> const> ConstPtr;

}; // struct RcvrZeroizeRequest_

typedef ::ros_sensor_msgs::RcvrZeroizeRequest_<std::allocator<void> > RcvrZeroizeRequest;

typedef boost::shared_ptr< ::ros_sensor_msgs::RcvrZeroizeRequest > RcvrZeroizeRequestPtr;
typedef boost::shared_ptr< ::ros_sensor_msgs::RcvrZeroizeRequest const> RcvrZeroizeRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_sensor_msgs::RcvrZeroizeRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_sensor_msgs::RcvrZeroizeRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ros_sensor_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'ros_sensor_msgs': ['/home/christian/lateralOffset/src/ros-sensor-msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ros_sensor_msgs::RcvrZeroizeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_sensor_msgs::RcvrZeroizeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_sensor_msgs::RcvrZeroizeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_sensor_msgs::RcvrZeroizeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_sensor_msgs::RcvrZeroizeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_sensor_msgs::RcvrZeroizeRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_sensor_msgs::RcvrZeroizeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "00be833a0082ac75852a29b8e8053002";
  }

  static const char* value(const ::ros_sensor_msgs::RcvrZeroizeRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x00be833a0082ac75ULL;
  static const uint64_t static_value2 = 0x852a29b8e8053002ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_sensor_msgs::RcvrZeroizeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_sensor_msgs/RcvrZeroizeRequest";
  }

  static const char* value(const ::ros_sensor_msgs::RcvrZeroizeRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_sensor_msgs::RcvrZeroizeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool clear_keys\n\
bool clear_rcvr_data\n\
bool clear_position_and_time\n\
";
  }

  static const char* value(const ::ros_sensor_msgs::RcvrZeroizeRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_sensor_msgs::RcvrZeroizeRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.clear_keys);
      stream.next(m.clear_rcvr_data);
      stream.next(m.clear_position_and_time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RcvrZeroizeRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_sensor_msgs::RcvrZeroizeRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_sensor_msgs::RcvrZeroizeRequest_<ContainerAllocator>& v)
  {
    s << indent << "clear_keys: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.clear_keys);
    s << indent << "clear_rcvr_data: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.clear_rcvr_data);
    s << indent << "clear_position_and_time: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.clear_position_and_time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_SENSOR_MSGS_MESSAGE_RCVRZEROIZEREQUEST_H
