// Generated by gencpp from file ros_sensor_msgs/SensorParams3Axis.msg
// DO NOT EDIT!


#ifndef ROS_SENSOR_MSGS_MESSAGE_SENSORPARAMS3AXIS_H
#define ROS_SENSOR_MSGS_MESSAGE_SENSORPARAMS3AXIS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <ros_sensor_msgs/Vector3Cov.h>
#include <ros_sensor_msgs/Vector3Cov.h>

namespace ros_sensor_msgs
{
template <class ContainerAllocator>
struct SensorParams3Axis_
{
  typedef SensorParams3Axis_<ContainerAllocator> Type;

  SensorParams3Axis_()
    : bias()
    , scaleFactor()  {
    }
  SensorParams3Axis_(const ContainerAllocator& _alloc)
    : bias(_alloc)
    , scaleFactor(_alloc)  {
  (void)_alloc;
    }



   typedef  ::ros_sensor_msgs::Vector3Cov_<ContainerAllocator>  _bias_type;
  _bias_type bias;

   typedef  ::ros_sensor_msgs::Vector3Cov_<ContainerAllocator>  _scaleFactor_type;
  _scaleFactor_type scaleFactor;





  typedef boost::shared_ptr< ::ros_sensor_msgs::SensorParams3Axis_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_sensor_msgs::SensorParams3Axis_<ContainerAllocator> const> ConstPtr;

}; // struct SensorParams3Axis_

typedef ::ros_sensor_msgs::SensorParams3Axis_<std::allocator<void> > SensorParams3Axis;

typedef boost::shared_ptr< ::ros_sensor_msgs::SensorParams3Axis > SensorParams3AxisPtr;
typedef boost::shared_ptr< ::ros_sensor_msgs::SensorParams3Axis const> SensorParams3AxisConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_sensor_msgs::SensorParams3Axis_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_sensor_msgs::SensorParams3Axis_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ros_sensor_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'ros_sensor_msgs': ['/home/christian/lateralOffset/src/ros-sensor-msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ros_sensor_msgs::SensorParams3Axis_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_sensor_msgs::SensorParams3Axis_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_sensor_msgs::SensorParams3Axis_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_sensor_msgs::SensorParams3Axis_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_sensor_msgs::SensorParams3Axis_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_sensor_msgs::SensorParams3Axis_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_sensor_msgs::SensorParams3Axis_<ContainerAllocator> >
{
  static const char* value()
  {
    return "24c3e2bb8a356470f1a6dba76b1bcfc1";
  }

  static const char* value(const ::ros_sensor_msgs::SensorParams3Axis_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x24c3e2bb8a356470ULL;
  static const uint64_t static_value2 = 0xf1a6dba76b1bcfc1ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_sensor_msgs::SensorParams3Axis_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_sensor_msgs/SensorParams3Axis";
  }

  static const char* value(const ::ros_sensor_msgs::SensorParams3Axis_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_sensor_msgs::SensorParams3Axis_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Vector3Cov bias\n\
Vector3Cov scaleFactor\n\
================================================================================\n\
MSG: ros_sensor_msgs/Vector3Cov\n\
geometry_msgs/Vector3 	value 		# unit\n\
float64[9] 				covariance 	# unit^2\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
# It is only meant to represent a direction. Therefore, it does not\n\
# make sense to apply a translation to it (e.g., when applying a \n\
# generic rigid transformation to a Vector3, tf2 will only apply the\n\
# rotation). If you want your data to be translatable too, use the\n\
# geometry_msgs/Point message instead.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::ros_sensor_msgs::SensorParams3Axis_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_sensor_msgs::SensorParams3Axis_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.bias);
      stream.next(m.scaleFactor);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SensorParams3Axis_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_sensor_msgs::SensorParams3Axis_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_sensor_msgs::SensorParams3Axis_<ContainerAllocator>& v)
  {
    s << indent << "bias: ";
    s << std::endl;
    Printer< ::ros_sensor_msgs::Vector3Cov_<ContainerAllocator> >::stream(s, indent + "  ", v.bias);
    s << indent << "scaleFactor: ";
    s << std::endl;
    Printer< ::ros_sensor_msgs::Vector3Cov_<ContainerAllocator> >::stream(s, indent + "  ", v.scaleFactor);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_SENSOR_MSGS_MESSAGE_SENSORPARAMS3AXIS_H
