// Generated by gencpp from file ros_sensor_msgs/SourceType.msg
// DO NOT EDIT!


#ifndef ROS_SENSOR_MSGS_MESSAGE_SOURCETYPE_H
#define ROS_SENSOR_MSGS_MESSAGE_SOURCETYPE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_sensor_msgs
{
template <class ContainerAllocator>
struct SourceType_
{
  typedef SourceType_<ContainerAllocator> Type;

  SourceType_()
    : type(0)  {
    }
  SourceType_(const ContainerAllocator& _alloc)
    : type(0)  {
  (void)_alloc;
    }



   typedef uint8_t _type_type;
  _type_type type;



  enum {
    SourceTypeUnknown = 0u,
    SourceTypeReceiver = 1u,
    SourceTypeNetwork = 2u,
    SourceTypeRinex = 3u,
    SourceTypeAny = 99u,
  };


  typedef boost::shared_ptr< ::ros_sensor_msgs::SourceType_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_sensor_msgs::SourceType_<ContainerAllocator> const> ConstPtr;

}; // struct SourceType_

typedef ::ros_sensor_msgs::SourceType_<std::allocator<void> > SourceType;

typedef boost::shared_ptr< ::ros_sensor_msgs::SourceType > SourceTypePtr;
typedef boost::shared_ptr< ::ros_sensor_msgs::SourceType const> SourceTypeConstPtr;

// constants requiring out of line definition

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_sensor_msgs::SourceType_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_sensor_msgs::SourceType_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ros_sensor_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'ros_sensor_msgs': ['/home/christian/lateralOffset/src/ros-sensor-msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ros_sensor_msgs::SourceType_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_sensor_msgs::SourceType_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_sensor_msgs::SourceType_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_sensor_msgs::SourceType_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_sensor_msgs::SourceType_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_sensor_msgs::SourceType_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_sensor_msgs::SourceType_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2b6f53ff512a57ec4523f25a3ccb8894";
  }

  static const char* value(const ::ros_sensor_msgs::SourceType_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2b6f53ff512a57ecULL;
  static const uint64_t static_value2 = 0x4523f25a3ccb8894ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_sensor_msgs::SourceType_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_sensor_msgs/SourceType";
  }

  static const char* value(const ::ros_sensor_msgs::SourceType_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_sensor_msgs::SourceType_<ContainerAllocator> >
{
  static const char* value()
  {
    return "## Source of data\n\
\n\
uint8 SourceTypeUnknown  = 0\n\
uint8 SourceTypeReceiver = 1\n\
uint8 SourceTypeNetwork  = 2\n\
uint8 SourceTypeRinex    = 3\n\
uint8 SourceTypeAny      = 99\n\
\n\
uint8 type\n\
";
  }

  static const char* value(const ::ros_sensor_msgs::SourceType_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_sensor_msgs::SourceType_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.type);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SourceType_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_sensor_msgs::SourceType_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_sensor_msgs::SourceType_<ContainerAllocator>& v)
  {
    s << indent << "type: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.type);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_SENSOR_MSGS_MESSAGE_SOURCETYPE_H
