// Generated by gencpp from file ros_sensor_msgs/WheelCounts.msg
// DO NOT EDIT!


#ifndef ROS_SENSOR_MSGS_MESSAGE_WHEELCOUNTS_H
#define ROS_SENSOR_MSGS_MESSAGE_WHEELCOUNTS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <ros_sensor_msgs/WheelCount.h>

namespace ros_sensor_msgs
{
template <class ContainerAllocator>
struct WheelCounts_
{
  typedef WheelCounts_<ContainerAllocator> Type;

  WheelCounts_()
    : header()
    , timestamp(0)
    , wheelCounts()  {
    }
  WheelCounts_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , timestamp(0)
    , wheelCounts(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _timestamp_type;
  _timestamp_type timestamp;

   typedef std::vector< ::ros_sensor_msgs::WheelCount_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::ros_sensor_msgs::WheelCount_<ContainerAllocator> >::other >  _wheelCounts_type;
  _wheelCounts_type wheelCounts;





  typedef boost::shared_ptr< ::ros_sensor_msgs::WheelCounts_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_sensor_msgs::WheelCounts_<ContainerAllocator> const> ConstPtr;

}; // struct WheelCounts_

typedef ::ros_sensor_msgs::WheelCounts_<std::allocator<void> > WheelCounts;

typedef boost::shared_ptr< ::ros_sensor_msgs::WheelCounts > WheelCountsPtr;
typedef boost::shared_ptr< ::ros_sensor_msgs::WheelCounts const> WheelCountsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_sensor_msgs::WheelCounts_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_sensor_msgs::WheelCounts_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ros_sensor_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'ros_sensor_msgs': ['/home/christian/lateralOffset/src/ros-sensor-msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ros_sensor_msgs::WheelCounts_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_sensor_msgs::WheelCounts_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_sensor_msgs::WheelCounts_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_sensor_msgs::WheelCounts_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_sensor_msgs::WheelCounts_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_sensor_msgs::WheelCounts_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_sensor_msgs::WheelCounts_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7b7b3ed86a61cee066b9a17b6b58914a";
  }

  static const char* value(const ::ros_sensor_msgs::WheelCounts_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7b7b3ed86a61cee0ULL;
  static const uint64_t static_value2 = 0x66b9a17b6b58914aULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_sensor_msgs::WheelCounts_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_sensor_msgs/WheelCounts";
  }

  static const char* value(const ::ros_sensor_msgs::WheelCounts_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_sensor_msgs::WheelCounts_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header   header\n\
uint32 timestamp  # [counts]\n\
WheelCount[] wheelCounts\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: ros_sensor_msgs/WheelCount\n\
uint32  wheel_count   # [counts]\n\
bool    dir_forward   # true if moving forward\n\
string  wheel_name\n\
";
  }

  static const char* value(const ::ros_sensor_msgs::WheelCounts_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_sensor_msgs::WheelCounts_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.timestamp);
      stream.next(m.wheelCounts);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WheelCounts_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_sensor_msgs::WheelCounts_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_sensor_msgs::WheelCounts_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "timestamp: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.timestamp);
    s << indent << "wheelCounts[]" << std::endl;
    for (size_t i = 0; i < v.wheelCounts.size(); ++i)
    {
      s << indent << "  wheelCounts[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::ros_sensor_msgs::WheelCount_<ContainerAllocator> >::stream(s, indent + "    ", v.wheelCounts[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_SENSOR_MSGS_MESSAGE_WHEELCOUNTS_H
