// Generated by gencpp from file wgs_conversions/WgsConversionResponse.msg
// DO NOT EDIT!


#ifndef WGS_CONVERSIONS_MESSAGE_WGSCONVERSIONRESPONSE_H
#define WGS_CONVERSIONS_MESSAGE_WGSCONVERSIONRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace wgs_conversions
{
template <class ContainerAllocator>
struct WgsConversionResponse_
{
  typedef WgsConversionResponse_<ContainerAllocator> Type;

  WgsConversionResponse_()
    : lla()
    , xyz()
    , enu()
    , xyz_cov()
    , enu_cov()  {
      lla.assign(0.0);

      xyz.assign(0.0);

      enu.assign(0.0);

      xyz_cov.assign(0.0);

      enu_cov.assign(0.0);
  }
  WgsConversionResponse_(const ContainerAllocator& _alloc)
    : lla()
    , xyz()
    , enu()
    , xyz_cov()
    , enu_cov()  {
  (void)_alloc;
      lla.assign(0.0);

      xyz.assign(0.0);

      enu.assign(0.0);

      xyz_cov.assign(0.0);

      enu_cov.assign(0.0);
  }



   typedef boost::array<double, 3>  _lla_type;
  _lla_type lla;

   typedef boost::array<double, 3>  _xyz_type;
  _xyz_type xyz;

   typedef boost::array<double, 3>  _enu_type;
  _enu_type enu;

   typedef boost::array<double, 9>  _xyz_cov_type;
  _xyz_cov_type xyz_cov;

   typedef boost::array<double, 9>  _enu_cov_type;
  _enu_cov_type enu_cov;





  typedef boost::shared_ptr< ::wgs_conversions::WgsConversionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wgs_conversions::WgsConversionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct WgsConversionResponse_

typedef ::wgs_conversions::WgsConversionResponse_<std::allocator<void> > WgsConversionResponse;

typedef boost::shared_ptr< ::wgs_conversions::WgsConversionResponse > WgsConversionResponsePtr;
typedef boost::shared_ptr< ::wgs_conversions::WgsConversionResponse const> WgsConversionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::wgs_conversions::WgsConversionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::wgs_conversions::WgsConversionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace wgs_conversions

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::wgs_conversions::WgsConversionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wgs_conversions::WgsConversionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wgs_conversions::WgsConversionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wgs_conversions::WgsConversionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wgs_conversions::WgsConversionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wgs_conversions::WgsConversionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::wgs_conversions::WgsConversionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c2cd2fea05ac4d6f35c95ca205c8b8ce";
  }

  static const char* value(const ::wgs_conversions::WgsConversionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc2cd2fea05ac4d6fULL;
  static const uint64_t static_value2 = 0x35c95ca205c8b8ceULL;
};

template<class ContainerAllocator>
struct DataType< ::wgs_conversions::WgsConversionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "wgs_conversions/WgsConversionResponse";
  }

  static const char* value(const ::wgs_conversions::WgsConversionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::wgs_conversions::WgsConversionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[3] lla\n\
float64[3] xyz\n\
float64[3] enu\n\
float64[9] xyz_cov\n\
float64[9] enu_cov\n\
";
  }

  static const char* value(const ::wgs_conversions::WgsConversionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::wgs_conversions::WgsConversionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.lla);
      stream.next(m.xyz);
      stream.next(m.enu);
      stream.next(m.xyz_cov);
      stream.next(m.enu_cov);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WgsConversionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::wgs_conversions::WgsConversionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::wgs_conversions::WgsConversionResponse_<ContainerAllocator>& v)
  {
    s << indent << "lla[]" << std::endl;
    for (size_t i = 0; i < v.lla.size(); ++i)
    {
      s << indent << "  lla[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.lla[i]);
    }
    s << indent << "xyz[]" << std::endl;
    for (size_t i = 0; i < v.xyz.size(); ++i)
    {
      s << indent << "  xyz[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.xyz[i]);
    }
    s << indent << "enu[]" << std::endl;
    for (size_t i = 0; i < v.enu.size(); ++i)
    {
      s << indent << "  enu[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.enu[i]);
    }
    s << indent << "xyz_cov[]" << std::endl;
    for (size_t i = 0; i < v.xyz_cov.size(); ++i)
    {
      s << indent << "  xyz_cov[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.xyz_cov[i]);
    }
    s << indent << "enu_cov[]" << std::endl;
    for (size_t i = 0; i < v.enu_cov.size(); ++i)
    {
      s << indent << "  enu_cov[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.enu_cov[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // WGS_CONVERSIONS_MESSAGE_WGSCONVERSIONRESPONSE_H
