# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from lateraloffset/PathDiagnostics.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import ros_sensor_msgs.msg
import std_msgs.msg

class PathDiagnostics(genpy.Message):
  _md5sum = "c5862f510f0fc37b9f5e8121e6c2f96c"
  _type = "lateraloffset/PathDiagnostics"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """## Diagnostics 

std_msgs/Header          header
ros_sensor_msgs/GpsTime  gpsTime

float32 lateralOffset

float32[] offsetVariance

float32 curvatureRating
float32[] localBodyFrameRPV


================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: ros_sensor_msgs/GpsTime
## GPS time structure
uint32          gps_week        # Full GPS week from (0:0:00 Jan 06, 1980)
float64         gps_seconds     # GPS seconds into week [sec]"""
  __slots__ = ['header','gpsTime','lateralOffset','offsetVariance','curvatureRating','localBodyFrameRPV']
  _slot_types = ['std_msgs/Header','ros_sensor_msgs/GpsTime','float32','float32[]','float32','float32[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,gpsTime,lateralOffset,offsetVariance,curvatureRating,localBodyFrameRPV

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(PathDiagnostics, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.gpsTime is None:
        self.gpsTime = ros_sensor_msgs.msg.GpsTime()
      if self.lateralOffset is None:
        self.lateralOffset = 0.
      if self.offsetVariance is None:
        self.offsetVariance = []
      if self.curvatureRating is None:
        self.curvatureRating = 0.
      if self.localBodyFrameRPV is None:
        self.localBodyFrameRPV = []
    else:
      self.header = std_msgs.msg.Header()
      self.gpsTime = ros_sensor_msgs.msg.GpsTime()
      self.lateralOffset = 0.
      self.offsetVariance = []
      self.curvatureRating = 0.
      self.localBodyFrameRPV = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_Idf().pack(_x.gpsTime.gps_week, _x.gpsTime.gps_seconds, _x.lateralOffset))
      length = len(self.offsetVariance)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.pack(pattern, *self.offsetVariance))
      buff.write(_get_struct_f().pack(self.curvatureRating))
      length = len(self.localBodyFrameRPV)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.pack(pattern, *self.localBodyFrameRPV))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.gpsTime is None:
        self.gpsTime = ros_sensor_msgs.msg.GpsTime()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 16
      (_x.gpsTime.gps_week, _x.gpsTime.gps_seconds, _x.lateralOffset,) = _get_struct_Idf().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.offsetVariance = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (self.curvatureRating,) = _get_struct_f().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.localBodyFrameRPV = struct.unpack(pattern, str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_Idf().pack(_x.gpsTime.gps_week, _x.gpsTime.gps_seconds, _x.lateralOffset))
      length = len(self.offsetVariance)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.offsetVariance.tostring())
      buff.write(_get_struct_f().pack(self.curvatureRating))
      length = len(self.localBodyFrameRPV)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.localBodyFrameRPV.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.gpsTime is None:
        self.gpsTime = ros_sensor_msgs.msg.GpsTime()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 16
      (_x.gpsTime.gps_week, _x.gpsTime.gps_seconds, _x.lateralOffset,) = _get_struct_Idf().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.offsetVariance = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      start = end
      end += 4
      (self.curvatureRating,) = _get_struct_f().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.localBodyFrameRPV = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_Idf = None
def _get_struct_Idf():
    global _struct_Idf
    if _struct_Idf is None:
        _struct_Idf = struct.Struct("<Idf")
    return _struct_Idf
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_f = None
def _get_struct_f():
    global _struct_f
    if _struct_f is None:
        _struct_f = struct.Struct("<f")
    return _struct_f
