(cl:in-package drtk-msg)
(cl:export '(HEADER-VAL
          HEADER
          GPSTIME-VAL
          GPSTIME
          SDFLOATINTEGERAMBIGUITIESL1-VAL
          SDFLOATINTEGERAMBIGUITIESL1
          SDFLOATINTEGERAMBIGUITIESL2-VAL
          SDFLOATINTEGERAMBIGUITIESL2
          NUMAVAILABLESVS-VAL
          NUMAVAILABLESVS
          LAMBDARATIO-VAL
          LAMBDARATIO
          LOCKEDLAMBDARATIO-VAL
          LOCKEDLAMBDARATIO
          BASEPRN-VAL
          BASEPRN
))